site_name: AI Infographics
site_description: 'AI Infographics is a collection of resources for creating interactive infographics using AI tools.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/infographics/'
repo_url: 'https://github.com/dmccreary/infographics'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Taxonomy: taxonomy.md
  - Slide Art: slide-art.md
  - Back of the Napkin: back-of-the-napkin.md
  - Causal Loop Diagrams: causal-loop-diagrams.md
  - MicroSims:
    - Introduction: sims/index.md
  - Research:
    - Intro: research/index.md
    - Open Source Tools: research/open-source-tools.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  logo: img/logo-192x192.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX